version: "3.9"

services:
  api:
    container_name: api
    image: hexastack/hexabot-api:latest
    env_file: .env
    ports:
      - 3000:3000
    networks:
      - db-network
      - app-network
    volumes:
      - api-data:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:3000/api/health"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  hexabot-frontend:
    container_name: frontend
    image: hexastack/hexabot-ui:latest
    env_file: .env
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      api:
        condition: service_healthy

  postgres:
    container_name: ${DB_HOST:-postgres}
    hostname: ${DB_HOST:-postgres}
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      db-network:
        aliases:
          - ${DB_HOST:-postgres}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${DB_NAME} -U ${DB_USERNAME}"
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  api-data:

networks:
  db-network:
  app-network:
