version: "3.9"

services:
  api:
    networks:
      - nlu-network
    depends_on:
      nlu-api:
        condition: service_healthy

  nlu-api:
    container_name: nlu-api
    image: hexastack/hexabot-nlu:latest
    env_file: .env
    networks:
      - nlu-network
    volumes:
      - nlu-data:/app/repos
    healthcheck:
      test: curl --fail http://localhost:5000/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  nlu-data:

networks:
  nlu-network:
