version: "3.9"

services:
  widget:
    build:
      context: ..
      dockerfile: packages/widget/Dockerfile
      target: development
    pull_policy: build
    volumes:
      - ../packages/widget/src:/app/packages/widget/src
