name: Publish Hexabot Widget NPM Package

on:
  push:
    tags:
      - "v2.*"
  workflow_dispatch: # Allow manual trigger

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          standalone: true
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --filter @hexabot/widget... --prod=false

      - name: Build the package
        run: pnpm --filter @hexabot/widget... run build

      - name: Determine release type
        id: determine-release
        run: |
          if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
            if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.0$ ]]; then
              echo "release=minor" >> $GITHUB_ENV
            elif [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "release=patch" >> $GITHUB_ENV
            else
              echo "release=none" >> $GITHUB_ENV
            fi
          else
            echo "release=none" >> $GITHUB_ENV
          fi

      - name: Login to npm
        if: env.release != 'none'
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        if: env.release != 'none'
        working-directory: packages/widget
        run: npm publish
